siteTitle = "Andrew Colclough - Designer, Developer, Illustrator"
siteDescr = "Designer | Developer | Illustrator"
siteAuthor = "Andrew Colclough"

siteTwitterUrl = "https://twitter.com/wtc"
siteGithubUrl = "https://github.com/andrewdc"
siteEmailUrl = "andrew.design@gmail.com"
siteDribbbleUrl ="https://dribbble.com/adc"

siteInstagram = "https://www.instagram.com/bullet_and_whiskey/"
siteLinkedin = "https://www.linkedin.com/in/andrewdc"

googleAnalyticsId = "UA-90869201-1"

linkPrefix = "/adc"
